### ISSUE TITLE
[Compatibility Request]: Enderlisious

### ISSUE THREAD

**Issue by Omgise** [GTMEGA/EndlessIDs#119]
### Other mod's name

Enderlisious

### Other mod's homepage

https://legacy.curseforge.com/minecraft/mc-mods/enderlicious

### Other mod's license

All Rights Reserved

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11291861/fml-client-latest.log)

### Description

https://user-images.githubusercontent.com/106000018/233529889-9d256530-03f3-4ec8-a9ab-3b32c05f55d0.mp4

**Comment by FalsePattern** [comment]
This should be fixed in 1.5.0

**Comment by Omgise** [comment]
Thanks, this bug has been fixed
