### ISSUE TITLE
[Bug]: Crash with ASJCORE ON Server 

### ISSUE THREAD

**Issue by quentin452** [GTMEGA/EndlessIDs#142]
### OS

Linux/BSD

### GPU

NVIDIA

### Modpack (Optional)

no modpack

### Game log

https://mega.nz/file/etM2TaiY#Yltk8KW5c9EyCRDUc2uYBYC_2Jv0Eyn8vSlLSHRvqLU

### Description

The crash appear only on server with asjcore and endless ids installed

i think the crash come from this class : https://raw.githubusercontent.com/FalsePattern/EndlessIDs/master/src/main/java/com/falsepattern/endlessids/asm/IETransformer.java

probably related to #130 

note : the issue start to appaer since endlessids-mc1.7.10-1.4.0-alpha0001+biometestvanilla

**Comment by FalsePattern** [comment]
Found the issue, i had some missing try/catch blocks in my transformer code, and some classes just do not like being transformed on serverside, because they have weird half-client half-server methods.
I'll turn this into a regular warning in the next hotfix, but it might permanently corrupt worlds if it turns out transforming said class is actually important, so make sure to create backups frequently.

**Comment by quentin452** [comment]
ok thx

**Comment by brandyyn** [comment]
> Found the issue, i had some missing try/catch blocks in my transformer code, and some classes just do not like being transformed on serverside, because they have weird half-client half-server methods. I'll turn this into a regular warning in the next hotfix, but it might permanently corrupt worlds if it turns out transforming said class is actually important, so make sure to create backups frequently.

was this ever pushed? someone was complaining about it on the alfheim server that they crash when trying to start their mc server with alfheim and eids, i haven't tried to run it on a server yet but i also run both mods.

**Comment by brandyyn** [comment]
@FalsePattern

**Comment by FalsePattern** [comment]
Send the full game log instead of just the crashlog, the crashlog contains no relevant information.

**Comment by FalsePattern** [comment]
Fixed in 1.5 beta 3
