### ISSUE TITLE
[Compatibility Request]: Angelica

### ISSUE THREAD

**Issue by Rimusp** [GTMEGA/EndlessIDs#156]
### Other mod's name

Angelica

### Other mod's homepage

https://github.com/GTNewHorizons/Angelica

### Other mod's license

AGPLv3

### Game log

[fml-client-latest.log](https://github.com/GTMEGA/EndlessIDs/files/13620313/fml-client-latest.log)

### Description

I dont even know if its possible to add compat from ur side but seems like they wont add support for endless ids as they use theire own version of neid

**Comment by FalsePattern** [comment]
It needs to be fixed on Angelica's side.
https://github.com/GTNewHorizons/Angelica/blob/c71c85ab2e3545b60d2dc11b8ba5f9a764e1abe5/src/main/java/com/gtnewhorizons/angelica/compat/ExtendedBlockStorageExt.java#L19

They need to add compat for EndlessIDs' block array edits in this constructor.

**Comment by FalsePattern** [comment]
Update: i've looked at Angelica's code, i will add some helper code into chunkapi that should make integration on their side as simple as calling a single helper method. I'm somewhat busy with IRL stuff right now, but i'll get to it once i'm free.

**Comment by Caedis** [comment]
Let me know when that is done and I can add the compat to Angelica

**Comment by FalsePattern** [comment]
I'm busy with university projects this week, i'll finish the API next week.

**Comment by FalsePattern** [comment]
Opened a PR on Angelica, discussion will continue there.

https://github.com/GTNewHorizons/Angelica/pull/94

**Comment by FalsePattern** [comment]
Done.
