### ISSUE TITLE
[Compatibility Request]: vanilla mobs are not displayed to players on the server

### ISSUE THREAD

**Issue by KempeR0744** [GTMEGA/EndlessIDs#163]
### Other mod's name

Techno-magic, 201 mods... the problem is exactly in endlessids and with three libraries

### Other mod's homepage

none

### Other mod's license

AGPLv3

### Game log

empty. as the game works correctly in single player, but when you play with a friend, he does not display vanilla mobs, but from other mods, the mobs are all displayed.

### Description

Hi everyone, I'm writing here for the first time, so don't kick me :).
In general, after installing the mod Endlessids, and adding 3 necessary mods or libraries. then I all very long customized and sorted id biomes. all worked. but the matter is not in this: when entering the server (when the player is on the server, example friend) - him do not display all the mobs from vanilla minecraft. but display all the mobs from other mods. but in the game (being in singleplayer) all correctly displayed.
Help me solve this problem!
p.s. variants with the selection of mods excluded, as I have installed 201 mods. and everything worked well, except for biomes. so I wanted to solve this problem to play at all 200%.
After a long correspondence on github it turned out that the problem was in a small option - entity id extender. After disabling it (mode "false"), everything is back to normal - all mobs are displayed, both vanilla and from other mods.

**Comment by LasmGratel** [comment]
This is very serious, I debugged for ~5 hours keep trying and finally found out this mod can cause the issue, it's so terrible
