### ISSUE TITLE
[Compatibility Request]: ThutMods 2.0

### ISSUE THREAD

**Issue by branman5949** [GTMEGA/EndlessIDs#175]
### Other mod's name

thutmods-2.0.jar

### Other mod's homepage

https://www.dropbox.com/sh/dnh7egnujs191sa/AADGFkDpSSW7PXOYR6TzyXpva?dl=0

### Other mod's license

Other open source license (please specify in the description)

### Game log

[crash-2024-04-14_07.53.35-server.txt](https://github.com/GTMEGA/EndlessIDs/files/14970571/crash-2024-04-14_07.53.35-server.txt)
[latest.log](https://github.com/GTMEGA/EndlessIDs/files/14970572/latest.log)

[fml-client-latest.log](https://github.com/GTMEGA/EndlessIDs/files/14970578/fml-client-latest.log)

### Description

when i try to spawn the volcano block it instantly crashes with EndlessIDs and I was wondering if you would get back into fixing compatibility with other mods and EndlessIDs again.

ALSO You will need this mod in order to load ThutMods:
https://www.curseforge.com/minecraft/mc-mods/forge-multi-part/files/2242993

Here is the Github Source Page:
https://github.com/Thutmose/Thut

**Comment by FalsePattern** [comment]
Should be fixed in 1.5.1

**Comment by branman5949** [comment]
it works!
