### ISSUE TITLE
[Compatibility Request]: OWG (Old World Gen)

### ISSUE THREAD

**Issue by branman5949** [GTMEGA/EndlessIDs#176]
### Other mod's name

OWG-1.0.3-1.7.10.jar

### Other mod's homepage

https://github.com/Ted80-Minecraft-Mods/Old-World-Gen?tab=readme-ov-file

### Other mod's license

Unlicense

### Game log

[fml-client-latest.log](https://github.com/GTMEGA/EndlessIDs/files/14973017/fml-client-latest.log)

[latest.log](https://github.com/GTMEGA/EndlessIDs/files/14973013/latest.log)

[crash-2024-04-14_20.54.57-server (WITH BOP).txt](https://github.com/GTMEGA/EndlessIDs/files/14973014/crash-2024-04-14_20.54.57-server.WITH.BOP.txt)

### Description

whenever i try to generate a world with the Old World Gen mod it crashes with EndlessIDs.

here's the link to download it
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3

**Comment by FalsePattern** [comment]
Should be fixed in 1.5.1

**Comment by branman5949** [comment]
it works!
