### ISSUE TITLE
Angelica x Endlessids crash when connecting to a server

### ISSUE THREAD

**Issue by brandyyn** [GTMEGA/EndlessIDs#180]
### OS

Windows

### GPU

NVIDIA

### Game log

[angelica x eids server crash.log](https://github.com/GTMEGA/EndlessIDs/files/15427421/angelica.x.eids.server.crash.log)

java.lang.NullPointerException: Cannot load from byte/boolean array because "this.field_76651_r" is null

Screen name: ERROR NullPointerException: Cannot invoke "Object.getClass()" because "this.this$0.field_71462_r" is null

### Description

steps to recreate:

start a server with endlessids

connect to server with endlessids + angelica

crash when joining the world

**Comment by brandyyn** [comment]
this is a huge issue as you can't play on a server at all with endlessids and angelica together. singleplayer works perfectly fine though

**Comment by FalsePattern** [comment]
This needs to be fixed on Angelica's side.

**Comment by FalsePattern** [comment]
Fixed in Angelica's master branch: https://github.com/GTNewHorizons/Angelica/commit/8a56ab8ca1e2274d39a690bce8dd9097f8e5c1a4
