### ISSUE TITLE
[Compatibility Request]: BiomeTweaker and Climate Control

### ISSUE THREAD

**Issue by Sunconure11** [GTMEGA/EndlessIDs#185]
### Other mod's name

BiomeTweaker and Climate Control

### Other mod's homepage

Read text

### Other mod's license

Other open source license (please specify in the description)

### Game log

[crash-2024-06-20_09.58.40-server.txt](https://github.com/user-attachments/files/15915353/crash-2024-06-20_09.58.40-server.txt)

### Description

https://www.curseforge.com/minecraft/mc-mods/climate-control-geographicraft

https://www.curseforge.com/minecraft/mc-mods/biometweaker

The two mods use two differing licenses.

**Comment by Sunconure11** [comment]
The issue is that both mods act really weird in regards to mods that assign more IDs on this version of MC.

**Comment by Sunconure11** [comment]
[crash-2024-06-20_10.33.19-client.txt](https://github.com/user-attachments/files/15915656/crash-2024-06-20_10.33.19-client.txt)

Extra Biomes XL also keeps trying to assign itself to your placeholder biome.

**Comment by Sunconure11** [comment]
This, in turn, screws up generation with stuff like RTG because it then places placeholder biomes in the form of mushroom island biomes. BoP is notably affected by this.

https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty

https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation

https://www.curseforge.com/minecraft/mc-mods/alternate-terrain-generation

**Comment by brandyyn** [comment]
> This, in turn, screws up generation with stuff like RTG because it then places placeholder biomes in the form of mushroom island biomes. BoP is notably affected by this.
> 
> https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
> 
> https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation
> 
> https://www.curseforge.com/minecraft/mc-mods/alternate-terrain-generation

this isn't a bug with endlessids, its a bug with bop, any default world that you havent selected as a biomesop world type will spawn mushroom biomes everywhere, the only way to fix this is to disable mushroom biomes in the bop config. it's a bug with bop, not endlessids.

but if i do recall correctly, climatecontrol doesnt work with endlessids, but i'll need to check to make sure

**Comment by brandyyn** [comment]
my attempt at creating a world with climatecontrol in my pack with endlessids:
[fml-client-latest.log](https://github.com/user-attachments/files/15942036/fml-client-latest.log)
[crash-2024-06-23_00.44.28-server.txt](https://github.com/user-attachments/files/15942037/crash-2024-06-23_00.44.28-server.txt)

**Comment by Sunconure11** [comment]
Out of curiosity, I decided to try this with the Gregtech New Horizons fork of Climate Control. Same error.

**Comment by Sunconure11** [comment]
My reasoning for trying their fork is that some mods they maintain contain various fixes for stuff that never got such as players moved to newer versions of MC.

**Comment by Sunconure11** [comment]
I've also noticed that only vanilla, Extra Biomes XL, and Thaumcraft biomes show up.

**Comment by Sunconure11** [comment]
![image](https://github.com/user-attachments/assets/c708c396-ef60-4148-9211-5a43d1f0674a)

**Comment by Sunconure11** [comment]
Requesting a possible look-over by two other devs that have committed recently, @Houstonruss and @Darek505

**Comment by Sunconure11** [comment]
https://github.com/GTMEGA/EndlessIDs/issues/189

Related issue

**Comment by FalsePattern** [comment]
Should be fixed in 1.5.3

**Comment by Sunconure11** [comment]
BiomeTweaker may need a patch.

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/user-attachments/files/16516627/latest.log)

**Comment by Sunconure11** [comment]
The crash with the other mod seemed to let up with updates to some existing mods.

When attempting to create a Realistic world with RTG though, I got this crash: https://pastebin.com/A6y7gc6i

**Comment by brandyyn** [comment]
Same issue here https://github.com/GTMEGA/EndlessIDs/issues/189#issuecomment-2294515113

**Comment by FalsePattern** [comment]
It should be fixed in the latest nightly, you can grab it here:
https://github.com/GTMEGA/EndlessIDs/actions/runs/10851105588/artifacts/1930260469
the mod jar is inside the zip file

**Comment by FalsePattern** [comment]
This bug is now tracked in #189
