### ISSUE TITLE
[Compatibility Request]: Ex Nihilo

### ISSUE THREAD

**Issue by God-Dnds** [GTMEGA/EndlessIDs#191]
### Other mod's name

Ex Nihilo

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/ex-nihilo

### Other mod's license

Other open source license (please specify in the description)

### Game log

[latest.log](https://github.com/user-attachments/files/16152603/latest.log)

### Description

Ex Nihilo crashs with "Invalid id 9626 - maximum id range exceeded."

**Comment by FalsePattern** [comment]
Increase the `extraBlockIDBits` value in the EndlessIDs config.
