### ISSUE TITLE
[Bug]: Client crash when joining server with DMod and entity extension turned on

### ISSUE THREAD

**Issue by githubgarry73** [GTMEGA/EndlessIDs#211]
### Game log

[fml-client-3.log](https://github.com/user-attachments/files/17466812/fml-client-3.log)

### Description

Game crashes when trying to enter a server with DMod while having the entity ID extension turned on. Works without the extension. Also works when disabling foxes in DMod config.

**Comment by brandyyn** [comment]
Should also mention the datawatcher extension is on and the foxes are set to higher than 31, but it also crashes when set to below 31(allegedly), i haven't tested this for myself though.

But to reiterate, turning off the entity extension fixes this or turning off the fox from DMOD, the fox uses like 5 datawatchers by itself.

This DOES NOT happen in singleplayer, only when joining a server. @FalsePattern

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via live chat HERE  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app) Regards
